# Number of UAVs
number_of_uavs: 3

#--------------------------------------------------------------------------------------------#
# Gazebo origin (lat-lon-alt) can be defined with 'map_frame' or with 'sim_origin' params
#--------------------------------------------------------------------------------------------#
# map frame (if we need a map to world transform)
# map_frame:
#   frame_id: "map"
#   parent_frame: "world"
#   units: "GPS"
#   translation: [37.558542, -5.931074, 7.89]
#   rotation: [0.0, 0.0, 0.0] # RPY

# sim_origin (if we only want to define Gazebo origin)
sim_origin: [37.558542, -5.931074, 7.89]

#--------------------------------------------------------------------------------------------#
# uav frames
#--------------------------------------------------------------------------------------------#

# uav_1_home frame
uav_1_home_frame:
  frame_id: "uav_1_home"
  parent_frame: "map"
  units: "m"
  translation: [-10.0, -10.0, 0.5]
  rotation: [0.0, 0.0, 0.0] # RPY

# uav_2_home frame
uav_2_home_frame:
  frame_id: "uav_2_home"
  parent_frame: "map"
  units: "m"
  translation: [-10.0, 10.0, 0.5]
  rotation: [0.0, 0.0, 0.0] # RPY

# uav_3_home frame
uav_3_home_frame:
  frame_id: "uav_3_home"
  parent_frame: "map"
  units: "m"
  translation: [10.0, 0.0, 0.5]
  rotation: [0.0, 0.0, 0.0] # RPY