arms_postures:
  names: ["zero", "home"]

  # initial posture must exist, but is not necessarily listed inside arms_posture/names
  initial:
    joint_names: ['q1_1', 'q1_2', 'q1_3', 'q1_4', 'q2_1', 'q2_2', 'q2_3', 'q2_4']
    joint_values: [0.0, 0.0, -1.57, 0.0, 0.0, 0.0, -1.57, 0.0]

  zero:
    joint_names: ['q1_1', 'q1_2', 'q1_3', 'q1_4', 'q2_1', 'q2_2', 'q2_3', 'q2_4']
    joint_values: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

  home:
    joint_names: ['q1_1', 'q1_2', 'q1_3', 'q1_4', 'q2_1', 'q2_2', 'q2_3', 'q2_4']
    joint_values: [0.0, 0.0, -1.57, 0.0, 0.0, 0.0, -1.57, 0.0]
